### ISSUE TITLE
copy_reg vs copyreg in alignment.py

### ISSUE THREAD

**Issue by vijender-singh** [wf8/sumac#2]
I was installing the package for a user in a (miniconda3) conda environment with python(3.7) and encounter the issue with `copy_reg`.  It appears that in python3 `copy_reg` have to be changed to `copyreg` in [alignments.py](https://github.com/wf8/sumac/blob/master/src/alignments.py) locations line number 13 and 200.  That get it going, so if anyone is facing same issue, please look into it.  Also for some reason for me the `util.py` module was not getting imported so I have to
1) Changed permission of util.py to 755

2) export  the the path the PATH variable.

The later might be unique to my system, but just in case anyone else is facing the same issue, so posting my troubleshooting here.

**Comment by wf8** [comment]
Thanks for this! SUMAC was written long ago for Python 2.7 and has never been updated for Python 3.*, these are helpful notes.
